name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_CHECKOV: false        # Turn off if you’re not using Terraform/CloudFormation
          VALIDATE_NATURAL_LANGUAGE: false # Optional, disables spellcheck-style linting
          DISABLE_ERRORS: false          # Keep as false to fail builds on lint errors
